services:
  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    container_name: nexus-terminal-frontend
    ports:
      - "18111:80"
    depends_on:
      - backend
      - rdp # Added rdp dependency
    networks:
      - nexus-terminal-network

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    env_file:
      - .env # Load environment variables from .env file in the root
    container_name: nexus-terminal-backend
    ports:
      - "18112:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      RDP_BACKEND_API_BASE: http://rdp:9090 # Add URL for backend to reach RDP service
    volumes:
      - ./data:/app/data
    networks:
      - nexus-terminal-network

  rdp:
    build:
      context: .
      dockerfile: packages/rdp/Dockerfile
    container_name: nexus-terminal-rdp
    environment:
      GUACD_HOST: guacd
      GUACD_PORT: 4822
      API_PORT: 9090 # Default API port for rdp service
      GUAC_WS_PORT: 8081 # Default WebSocket port for rdp service
      FRONTEND_URL: http://frontend # Allow CORS from frontend container
      MAIN_BACKEND_URL: http://backend:3001 # Allow CORS from backend container
      NODE_ENV: production
    networks:
      - nexus-terminal-network
    depends_on:
      - guacd
      - backend

  guacd:
    image: guacamole/guacd:latest
    container_name: nexus-terminal-guacd
    networks:
      - nexus-terminal-network
    restart: unless-stopped

networks:
  nexus-terminal-network:
    driver: bridge