services:
  frontend:
    image: heavrnl/nexus-terminal-frontend
    container_name: nexus-terminal-frontend
    ports:
      - "18111:80"
    depends_on:
      - backend
    networks:
      - nexus-terminal-network

  backend:
    image: heavrnl/nexus-terminal-backend
    container_name: nexus-terminal-backend
    ports:
      - "18112:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
    volumes:
      - ./data:/app/data
    networks:
      - nexus-terminal-network


networks:
  nexus-terminal-network:
    driver: bridge
