services:
  frontend:
    image: heavrnl/nexus-terminal-frontend:latest
    container_name: nexus-terminal-frontend
    ports:
      - "18111:80"
    depends_on:
      - backend
      - rdp
    networks:
      - nexus-terminal-network

  backend:
    image: heavrnl/nexus-terminal-backend:latest
    container_name: nexus-terminal-backend
    env_file:
      - .env    
    environment:
      NODE_ENV: production
      PORT: 3001
      RDP_BACKEND_API_BASE: http://rdp:9090
    volumes:
      - ./data:/app/data
    networks:
      - nexus-terminal-network

  rdp:
    image: heavrnl/nexus-terminal-rdp:latest
    container_name: nexus-terminal-rdp
    environment:
      GUACD_HOST: guacd
      GUACD_PORT: 4822
      API_PORT: 9090
      GUAC_WS_PORT: 8081
      FRONTEND_URL: http://frontend
      MAIN_BACKEND_URL: http://backend:3001
      NODE_ENV: production
    networks:
      - nexus-terminal-network
    depends_on:
      - guacd
      - backend

  vnc:
    image: heavrnl/nexus-terminal-vnc:latest
    container_name: nexus-terminal-vnc
    environment:
      GUACD_HOST: guacd
      GUACD_PORT: 4822
      API_PORT: 9091
      GUAC_WS_PORT: 8082
      FRONTEND_URL: http://frontend
      MAIN_BACKEND_URL: http://backend:3001
      NODE_ENV: production
    networks:
      - nexus-terminal-network
    depends_on:
      - guacd
      - backend

  guacd:
    image: guacamole/guacd:latest
    container_name: nexus-terminal-guacd
    networks:
      - nexus-terminal-network
    restart: unless-stopped

networks:
  nexus-terminal-network:
    driver: bridge
    name: nexus-terminal-network
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd01::/80    
          gateway: fd01::1    
